#!/bin/bash

source database.sh

execute_deemix () {
	echo https://www.deezer.com/us/playlist/$1
	deemix -p $dl_dir https://www.deezer.com/us/playlist/$1
	echo
}

dl_archives () {
	for str in ${archives_id[@]}; do
		echo "--- DOWNLOAD ARCHIVES ---"
		execute_deemix $str
	done
}

dl_test () {
	for str in ${test_id[@]}; do
		echo "--- DOWNLOAD TEST ---"
		execute_deemix $str
	done
}

dl_night () {
	for str in ${night_id[@]}; do
		echo "--- DOWNLOAD NIGHT ---"
		execute_deemix $str
	done
}

dl_soiree () {
	for str in ${soiree_id[@]}; do
		echo "--- DOWNLOAD SOIREE ---"
		execute_deemix $str
	done
}

dl_rap_us () {
	for str in ${rap_us_id[@]}; do
		echo "--- DOWNLOAD RAP US ---"
		execute_deemix $str
	done
}

dee_main () {
	if [ "$1" = "archives" ]; then
		dl_archives
	elif [ "$1" = "night" ]; then
		dl_night
	elif [ "$1" = "rap_us" ]; then
		dl_rap_us
	elif [ "$1" = "soiree" ]; then
		dl_soiree
	elif [ "$1" = "test" ]; then
		dl_test
	else
		echo "No valid argument : $1"
		exit 2
	fi
}

dee_check_errors () {
	echo -e "--- LOG ---\n" > ${dir}log

	for subdir in "$dl_dir"*; do
		if [ -d "$subdir" ]; then
			for file in "$subdir"/*; do
				if [ -f "$file" ] && [ "$file" == "$subdir/errors.txt" ]; then
					cat "$file" >> ${dl_dir}log
					echo "--- ERRORS in $subdir --- (see ${dl_dir}log)"
				fi
			done
		fi
	done
}

dee_main $1
dee_check_errors
