#!/bin/bash

#ls | wc -l; echo "" ;ls | tail -n3

dir="${HOME}/Musique/deesh/"

archives_id=("10240340962" "10240340502" "10240338942" "10212303502" \
		"10212302862" "10465819782")

test_id=("11199853444", "11199852304")

execute_deemix () {
	echo https://www.deezer.com/us/playlist/$1
	deemix -p $dir https://www.deezer.com/us/playlist/$1
	echo
}

dl_archives () {
	for str in ${archives_id[@]}; do
		echo "--- DOWNLOAD ARCHIVES ---"
		execute_deemix $str
	done
}

dl_test () {
	for str in ${test_id[@]}; do
		echo "--- DOWNLOAD TEST ---"
		execute_deemix $str
	done
}

if [ "$1" = "archives" ]; then
	dl_archives
elif [ "$1" = "test" ]; then
	dl_test
else
	echo "No valid argument : $1"
	exit 2
fi

echo -e "--- LOG ---\n" > ${dir}log

for subdir in "$dir"/*; do
	if [ -d "$subdir" ]; then
    # Boucle à travers chaque fichier dans le sous-dossier
		for file in "$subdir"/*; do
			if [ -f "$file" ] && [ "$file" == "$subdir/errors.txt" ]; then
				cat "$file" >> ${dir}log
				echo "--- ERRORS in $subdir --- (see ${dir}log)"
			fi
		done
	fi
done
